# Stubs para módulos .NET (CLR)
from typing import Any

clr: Any

class System:
    class IO:
        class File: ...
        class FileAccess: ...
        class FileMode: ...
        class FileShare: ...
    class Windows:
        class Window: ...
        class Markup:
            class XamlReader: ...
    class String: ...
